### ISSUE TITLE
Does the program need special configuration before it runs?

### ISSUE THREAD

**Issue by ViolentButcher** [VITA-Group/AutoGAN#13]
Hi, thanks for providing the source code. I have trained the optimal network architecture reported in this paper for several times (by using the command 'sh exps/autogan_cifar10_a.sh'), but it is surprising that the FID value is always beyond 13. So I wonder whether the program need special configuration before it runs (I just use the raw configuration now).

**Comment by GongXinyuu** [comment]
Hi, there's no additional training tricks during training. Could you provide me with your obtained FID value?
