### ISSUE TITLE
Run seash.py or train.py with an error as follows：

### ISSUE THREAD

**Issue by yandong667** [VITA-Group/AutoGAN#20]
![image](https://user-images.githubusercontent.com/43993301/100564809-0233dc80-32fd-11eb-881b-9056d7e149d7.png)
![image](https://user-images.githubusercontent.com/43993301/100564819-07912700-32fd-11eb-827f-1657d0e39262.png)

**Comment by GongXinyuu** [comment]
May I know your tensorflow version?

**Comment by yandong667** [comment]
tf-gpu=1.13.1，大佬能否加下qq或者微信呢?&nbsp;有关模型问题还想跟您交流下~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/AutoGAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月1日(星期二) 中午12:20
收件人:&nbsp;"VITA-Group/AutoGAN"<AutoGAN@noreply.github.com&gt;;
抄送:&nbsp;"风还在发端"<775301251@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VITA-Group/AutoGAN] Run seash.py or train.py with an error as follows： (#20)





 
May I know your tensorflow version?

**Comment by GongXinyuu** [comment]
> tf-gpu=1.13.1，大佬能否加下qq或者微信呢?&nbsp;有关模型问题还想跟您交流下~
> […](#)

Sorry for the late reply. Can you try `tensorflow-gpu==1.12.0`?
You can add me with Wechat id:`xinyu_gong`.

**Comment by Chen-Bo-Yang** [comment]
I add two lines, show in below, for replace "import tensorflow as tf" is avalible for me.
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior()
reference: https://github.com/VITA-Group/TransGAN/blob/master/utils/inception_score.py
