### ISSUE TITLE
Trouble with training discovered GANs

### ISSUE THREAD

**Issue by VinulaUthsara** [VITA-Group/AutoGAN#21]
I am using Google Colab to train a GAN (after executing search) or the GAN searched in the research paper according to the instructions mentioned in the 'README.md' but the following error keeps happening.

![Screenshot (5)](https://user-images.githubusercontent.com/39290953/101818520-fdb3c300-3b49-11eb-885d-1b3254828574.png)

Traceback (most recent call last):
  File "train.py", line 167, in <module>
    main()
  File "train.py", line 138, in main
    inception_score, fid_score = validate(args, fixed_z, fid_stat, gen_net, writer_dict)
  File "/content/AutoGAN/functions.py", line 279, in validate
    img_grid = make_grid(sample_imgs, nrow=5, normalize=True, scale_each=True)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 75, in make_grid
    norm_range(t, range)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 71, in norm_range
    norm_ip(t, float(t.min()), float(t.max()))
  File "/usr/local/lib/python3.6/dist-packages/torchvision/utils.py", line 64, in norm_ip
    img.clamp_(min=min, max=max)
RuntimeError: Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by GongXinyuu** [comment]
May I know your torch version?

**Comment by GongXinyuu** [comment]
You can unblock yourself temporarily by setting `writer_dict` to `None` at this line. https://github.com/VITA-Group/AutoGAN/blob/25fbc6871b760cef5ae13c376d785e7b887109e2/train_derived.py#L141

**Comment by VinulaUthsara** [comment]
Torch version on Google Colab is : 1.7.0+cu101

**Comment by GongXinyuu** [comment]
Can u try to use pytorch 1.1.0 instead?
